plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    compileSdk 36
    namespace 'com.gengee.insaitlib'
    defaultConfig {
        minSdk 24
        targetSdk 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    sourceSets {
        main {
            jniLibs.srcDir 'libs'
        }
    }

    buildFeatures {
        viewBinding true
    }
    namespace 'com.gengee.insaitlib'
}

dependencies {

    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'

    /*
    这是因为implementation只能用于当前的module,倘若在库中用这种方式设置依赖,我们在app的module就引用不到.但是api或compile可以.
    */
    project.ext.room_version = "2.4.3"
    api "androidx.room:room-runtime:2.4.3"
    api "androidx.room:room-ktx:2.4.3"
    kapt "androidx.room:room-compiler:2.4.3" ///  需要在工程的build.gradle中添加

    // ViewModel
    api 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    // ViewModel utilities for Compose
    api 'androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1'
    // LiveData
    api 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.1'
    // optional - helpers for implementing LifecycleOwner in a Service
    api 'androidx.lifecycle:lifecycle-service:2.6.1'

    api 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'

    //  mmkv
    api 'com.tencent:mmkv:2.2.2'

    api 'com.google.code.gson:gson:2.10'
    //  android util code
    api 'com.blankj:utilcodex:1.31.1'

    api 'io.coil-kt:coil:2.3.0'
    //  弹窗
    api 'com.github.li-xiaojun:XPopup:2.9.19'

    // okhttp
    def okhttp_version = "4.9.3"
    api "com.squareup.okhttp3:okhttp:$okhttp_version"
    api "com.squareup.okhttp3:logging-interceptor:$okhttp_version"

    //  JetPackMvvm 一个Jetpack结合MVVM的快速开发框架，
    //  基于MVVM模式集成谷歌官方推荐的JetPack组件库：LiveData、ViewModel、Lifecycle、Navigation组件
    api 'com.github.hegaojian:JetpackMvvm:1.2.7'
}