apply plugin: 'com.android.application'
apply plugin: 'com.huawei.agconnect'

android {
    dataBinding {
        enabled true
    }

    signingConfigs {
        config {
            keyAlias 'weather'
            keyPassword 'Tq123456'
            storeFile file('../archive/weather.jks')
            storePassword 'Tq123456'
        }
    }

    compileSdkVersion 31

    defaultConfig {
        applicationId "com.goodtech.tq"
        minSdkVersion 19
        targetSdkVersion 31
        versionCode 591
        versionName "5.9.1"
        signingConfig signingConfigs.config
        multiDexEnabled true

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        ndk {
            //选择要添加的对应 cpu 类型的 .so 库。
            abiFilters 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'x86_64'
        }

        manifestPlaceholders = [
                JPUSH_PKGNAME: applicationId,
                JPUSH_APPKEY : "e2416540f4d3f0081fbef6df", //JPush 上注册的包名对应的 Appkey.
                JPUSH_CHANNEL : "developer-default", //暂时填写默认值即可.
                MEIZU_APPKEY : "MZ-3465e4112e2141f6b1438a648a5f6670",
                MEIZU_APPID : "MZ-146740",
                XIAOMI_APPID : "MI-2882303761517596193",
                XIAOMI_APPKEY : "MI-5321759614193",
                OPPO_APPKEY : "OP-86qoYufhhbWG84k0gkg0SScc0",
                OPPO_APPID : "OP-3574478",
                OPPO_APPSECRET : "OP-254Ebdc6DA2c044f855c2EebC89041f",
                VIVO_APPKEY : "af805fb3b61c6f4daf4e082c506b6275",
                VIVO_APPID : "100111470"
        ]
    }

    flavorDimensions "default"
    productFlavors {
        anzhi {
            buildConfigField 'int', 'BAIDU_CHANNEL', '999'
            manifestPlaceholders=[app_name:"苹果天气预报", umeng_channel:"anzhi"]
        }
        baidu {
            buildConfigField 'int', 'BAIDU_CHANNEL', '1'
            manifestPlaceholders=[app_name:"日历天气预报", umeng_channel:"baidu"]
        }
        huawei {
            buildConfigField 'int', 'BAIDU_CHANNEL', '8'
            manifestPlaceholders=[app_name:"天气预报纯净版", umeng_channel:"huawei"]
        }
        meizu {
            buildConfigField 'int', 'BAIDU_CHANNEL', '13'
            manifestPlaceholders=[app_name:"天气：天气预报", umeng_channel:"meizu"]
        }
        oppo {
            buildConfigField 'int', 'BAIDU_CHANNEL', '6'
            manifestPlaceholders=[app_name:"预知天气预报", umeng_channel:"oppo"]
        }
        sougou {
            buildConfigField 'int', 'BAIDU_CHANNEL', '4'
            manifestPlaceholders=[app_name:"天气预报-日历天气", umeng_channel:"sougou"]
        }
        tuiguang1 {
            buildConfigField 'int', 'BAIDU_CHANNEL', '9'
            manifestPlaceholders=[app_name:"预知天气预报", umeng_channel:"tuiguang1"]
        }
        tuiguang2 {
            buildConfigField 'int', 'BAIDU_CHANNEL', '9'
            manifestPlaceholders=[app_name:"天气预报", umeng_channel:"tuiguang2"]
        }
        vivo {
            buildConfigField 'int', 'BAIDU_CHANNEL', '7'
            manifestPlaceholders=[app_name:"天气-苹果天气预报", umeng_channel:"vivo"]
        }
        wdj {
            buildConfigField 'int', 'BAIDU_CHANNEL', '999'
            manifestPlaceholders=[app_name:"日历天气", umeng_channel:"wandoujia"]
        }
        xiaomi {
            buildConfigField 'int', 'BAIDU_CHANNEL', '10'
            manifestPlaceholders=[app_name:"天气预报-天气", umeng_channel:"xiaomi"]
        }
        yyb {
            buildConfigField 'int', 'BAIDU_CHANNEL', '9'
            manifestPlaceholders=[app_name:"天气预报", umeng_channel:"yyb"]
        }
    }

    def fileArray = []
    // 自定义APK安装包名
    android.applicationVariants.all {
        variant ->
            variant.outputs.all {
                outputFileName = "${defaultConfig.applicationId}-${getTime()}.apk"
            }
    }

    build {
        //build命令加入这段代码
        doLast() {
            //遍历文件数组并进行操作
            outforEachFile(fileArray)
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
        debug {
            signingConfig signingConfigs.config
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

static def getTime() {
    return new Date().format("yyMMdd", TimeZone.getDefault())
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation project(':cropimage')
    /// 流量聚合
    implementation project(path:':mediationAdapters:TTAdapter')
    implementation project(path:':mediationAdapters:BDAdapter')
    implementation project(path:':mediationAdapters:KSAdapter')
    implementation project(path:':mediationAdapters:Util')

    implementation 'com.google.android.material:material:1.3.0'
    //noinspection GradleCompatible
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    //noinspection GradleCompatible
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    //noinspection GradleCompatible
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.viewpager2:viewpager2:1.0.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
//    implementation 'org.litepal.android:core:1.4.1'
    //网络加载图片工具
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    // umeng
    //集成示例
    implementation 'com.umeng.umsdk:common:9.4.6'//必选
    implementation 'com.umeng.umsdk:asms:1.5.0'//必选
    //网络请求
    implementation 'com.squareup.okhttp3:okhttp:4.9.1'
    implementation 'com.squareup.okio:okio:2.10.0'
    implementation 'com.google.code.gson:gson:2.8.6'
    //eventbus
    implementation 'org.greenrobot:eventbus:3.2.0'

    implementation 'com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:1.0.0'
    //  下拉刷新控件
    implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.2'
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
//    implementation 'com.tencent.wcdb:wcdb-android:1.0.2'
    implementation 'androidx.multidex:multidex:2.0.1'
    //  适配器BaseRecyclerViewAdapterHelper
    implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.4'
    //  android util code
    implementation 'com.blankj:utilcodex:1.30.6'
    //  flex css布局
    implementation 'com.google.android:flexbox:2.0.1'
    //  日历
    implementation 'com.haibin:calendarview:3.7.1'
    //  mmkv存储
    implementation 'com.tencent:mmkv-static:1.2.7'
    //  权限请求
//    implementation 'com.github.tbruyelle:rxpermissions:0.12'
    implementation 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.4@aar'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

    implementation 'com.github.gzu-liyujiang.AndroidPicker:Common:3.1.2'
    implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelPicker:3.1.2'
    //微信开放平台，登录
    implementation 'com.tencent.mm.opensdk:wechat-sdk-android-with-mta:5.4.0'
    //  相机/相册
    implementation 'io.github.lucksiege:pictureselector:v2.7.3-rc08'

    implementation 'cn.jiguang.sdk:jcore:3.1.2'  // 此处以JCore 2.7.2 版本为例。
    implementation 'cn.jiguang.sdk:jpush:4.5.0'  // 此处以JPush 4.0.0 版本为例
    // 接入华为厂商
    implementation 'com.huawei.hms:push:6.1.0.300'
    implementation 'cn.jiguang.sdk.plugin:huawei:4.5.0'// 极光厂商插件版本与接入 JPush 版本保持一致，下同
    // 接入 FCM 厂商
//    implementation 'com.google.firebase:firebase-messaging:21.0.1'
//    implementation 'cn.jiguang.sdk.plugin:fcm:4.0.0'
    // 接入魅族厂商
    implementation 'cn.jiguang.sdk.plugin:meizu:4.5.0'
    // 接入 VIVO 厂商
    implementation 'cn.jiguang.sdk.plugin:vivo:4.5.0'
    // 接入 OPPO 厂商
    implementation 'cn.jiguang.sdk.plugin:oppo:4.5.0'
    // 接入小米厂商
    implementation 'cn.jiguang.sdk.plugin:xiaomi:4.5.0'
}
