apply plugin: 'com.android.library'

android {
    namespace "cn.gengee.cropimage"
    compileSdkVersion 31

    defaultConfig {
        minSdkVersion 18
        targetSdkVersion 31

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    // 无法访问 dl.google.com 时，release 的 vital lint / 注解抽取会拉取 lint 全家桶；本地库可关闭以免构建失败
    lint {
        checkReleaseBuilds false
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation ('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'androidx.appcompat:appcompat:1.0.0'
    testImplementation  'junit:junit:4.12'
}
